palabras = ["aire", "ojos", "piel", "joven", "viejo", "alto", 
"bajo", "pequeño", "gordo", "delgado", "bella", "azul", "verde", "negro", "sombrero", 
"trueno", "altavoz", "radio","comer", "dulce", "salado", "perfume", "despertarse", "vestirse",
"corbata", "gemelos", "paraguas", "plata", "oro", "perla", "diamante", "esmeralda", 
"anillo", "pulsera", "reloj", "camisa", "zapatos", "pelo", "maquillaje", "dedo", "hueso", "cara", "ojo", "calor", "ambulancia", "enfermera", 
"aplaudir", "teatro", "circo", "mago", "disco", "propina", "regalo", "fiesta", "vela", "alfombra", 
"puerta", "ventana", "cortina", "escritorio", "cuadro", "juguete", "alquiler", "casa", "pared", 
"farmacia", "vitaminas", "pastillas", "dentista", "ciego", "correr", "caminar", "regresar", "saltar", 
"cerrar", "nombre", "mujer", "hombre", "soltero", "novio", "nacer", "vivir", "edad",
"trabajar", "cobrar", "azafata", "artista", "panadero", "carpintero", "cocinero", "maestro", "bombero", 
"juez", "modelo", "pintor", "piloto", "secretaria", "taxista", "escritor", "jefe", 
"margarita", "amapola", "rosa", "girasol", "violeta", "gato", "perro", "vaca", "pato", "oveja", "conejo", "pez", 
"oso", "jirafa", "mariposa", "foca", "tigre", "paloma", "cisne", "mosquito", "hormiga", 
"llover", "nevar", "nublado", "soleado", "clima", "rayo", "nieve", "sol", "viento", "padre", "madre", "hijo", 
"jubilado", "empleo", "industria", "taller", "tienda", "vacaciones", "sueldo", "impuesto", 
"locura", "humor", "inteligencia", "orgullo", "timidez", "valiente", "aburrido", "loco", "divertido", "bueno", "feliz", 
"amable", "pobre", "serio", "extraño", "gritar", "llorar", "suspirar", "preocupado", "risa", "amor", "suerte", 
"enamorado", "apagar", "luz", "color", "lupa", "claro", "cantar", "silbar", "voz", 
"museo", "estatua", "fuente", "turista", "manejar", "acelerar", "frenar", "cruzar", "reparar",  
"desayunar", "leer", "dormirse", "toalla", "almuerzo", "sopa", "agua", "leche", "jugo", "sal", "pimienta", 
"menta", "canela", "mayonesa", "pan", "mantequilla", "miel", "manzana", "pera", "durazno", 
"cereza", "papa", "lechuga", "arroz", "pollo","hamburguesa", "camarones", "tortilla", "helado", 
"chocolate", "galletas", "limpiar", "cortar", "hervir", "planchar", "aspiradora", "plancha", "horno",
"vaso", "cafetera","comprar", "gastar", "vender", "barato", "caro", "gratis", "cliente", "bolsa", "precio", "recibo", "ascensor", "pelota", "bicicleta", 
"estadio", "gol", "leer", "dibujar", "cantar", "bailar", "libro", "revista", "cine", "pala", 
"cocina", "hielo", "piano", "cartas", "pesca", "radio", "noticias", "televisor", "documental", "anuncio", 
"chimenea", "comedor", "plaza", "calle", "estacionamiento", "parque", "puente", "puerto", "edificio", "escuela", 
"conductor", "curva", "campo", "bosque", "huerto", "selva", "tronco", "rama", "flor", "hoja", "cedro", "roble", "pino", "tallo", "clavel", 
"abuela", "estudioso", "aula", "tiza", "regla", "computadora", "diccionario"]